name: Main

on: [push]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Build
        run: |
          cd src
          dotnet build

      - name: CI Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: ./src/bin/Debug/net6.0