name: Main

on: [push]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Build
        run: |
          cd src
          dotnet build

      - name: Tag
        id: tagcount
        run: |
          echo "TAG_NAME=v$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ steps.tagcount.outputs.TAG_NAME }}
          name: Release ${{ steps.tagcount.outputs.TAG_NAME }}
          files: |
            ./src/bin/Debug/net6.0/*
            LICENSE
            README.md